version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://json-server:3001
    depends_on:
      - json-server

  json-server:
    image: clue/json-server
    working_dir: /data
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3001:3001"
    command: json-server --watch db.json --host 0.0.0.0 --port 3001